import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const features = [
  {
    title: "AI Itinerary",
    description:
      "Get a personalized day-by-day travel plan generated by GPT-4o, tailored to your destination and trip length.",
  },
  {
    title: "Weather Forecast",
    description:
      "See the real weather forecast for your travel dates so you can pack and plan accordingly.",
  },
  {
    title: "Destination Photos",
    description:
      "Browse curated photos of attractions at your destination, sourced directly from TripAdvisor.",
  },
  {
    title: "Cost & Exchange Rate",
    description:
      "Get rough daily cost estimates in your home currency, plus live exchange rates for the destination.",
  },
];

export default function Home() {
  return (
    <div className="min-h-screen flex flex-col">
      {/* Hero */}
      <main className="flex-1 flex flex-col items-center justify-center text-center px-6 py-24 space-y-8">
        <h1 className="text-4xl sm:text-5xl font-bold tracking-tight">
          Plan Your Perfect Trip with AI
        </h1>
        <p className="text-lg text-muted-foreground max-w-xl">
          Enter your destination and travel dates. Our AI creates a complete itinerary
          with weather, photos, attractions, and cost estimates — in seconds.
        </p>
        <Button asChild size="lg">
          <Link href="/trip">Start Planning</Link>
        </Button>

        {/* Feature cards */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 max-w-3xl w-full mt-8 text-left">
          {features.map((f) => (
            <Card key={f.title}>
              <CardHeader>
                <CardTitle className="text-base">{f.title}</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-muted-foreground">{f.description}</p>
              </CardContent>
            </Card>
          ))}
        </div>
      </main>

      <footer className="py-6 text-center text-sm text-muted-foreground border-t">
        Smart Travel Designer — AI-powered trip planning
      </footer>
    </div>
  );
}
