# app/services/utils.py

import pycountry

# Manually defined fallback for special currency zones
special_currency_regions = {
    "European Union": "EUR",
    "CEMAC": "XAF",
    "Organisation of Eastern Caribbean States": "XCD",
    "International Monetary Fund": "XDR",
    "CFA": "XOF",
    "Collectivités d'Outre-Mer": "XPF",
}

# Manual mapping where pycountry doesn't give currency
manual_country_currency_map = {
    "France": "EUR",
    "Germany": "EUR",
    "Italy": "EUR",
    "Spain": "EUR",
    "Portugal": "EUR",
    "Austria": "EUR",
    "Belgium": "EUR",
    "Netherlands": "EUR",
    "Greece": "EUR",
    "Finland": "EUR",
    "Ireland": "EUR",
    "Slovakia": "EUR",
    "Slovenia": "EUR",
    "Estonia": "EUR",
    "Latvia": "EUR",
    "Lithuania": "EUR",
    "Cyprus": "EUR",
    "Luxembourg": "EUR",
    "Malta": "EUR",
    "Monaco": "EUR",
    "Vatican City": "EUR",
    "San Marino": "EUR",
    "Kosovo": "EUR",
    "Montenegro": "EUR",
    "United Arab Emirates": "AED",
    "Afghanistan": "AFN",
    "Albania": "ALL",
    "Armenia": "AMD",
    "Netherlands Antilles": "ANG",
    "Angola": "AOA",
    "Argentina": "ARS",
    "Australia": "AUD",
    "Aruba": "AWG",
    "Azerbaijan": "AZN",
    "Bosnia and Herzegovina": "BAM",
    "Barbados": "BBD",
    "Bangladesh": "BDT",
    "Bulgaria": "BGN",
    "Bahrain": "BHD",
    "Burundi": "BIF",
    "Bermuda": "BMD",
    "Brunei": "BND",
    "Bolivia": "BOB",
    "Brazil": "BRL",
    "Bahamas": "BSD",
    "Bhutan": "BTN",
    "Botswana": "BWP",
    "Belarus": "BYN",
    "Belize": "BZD",
    "Canada": "CAD",
    "Democratic Republic of the Congo": "CDF",
    "Switzerland": "CHF",
    "Chile": "CLP",
    "China": "CNY",
    "Colombia": "COP",
    "Costa Rica": "CRC",
    "Cuba": "CUP",
    "Cape Verde": "CVE",
    "Czech Republic": "CZK",
    "Djibouti": "DJF",
    "Denmark": "DKK",
    "Dominican Republic": "DOP",
    "Algeria": "DZD",
    "Egypt": "EGP",
    "Eritrea": "ERN",
    "Ethiopia": "ETB",
    "European Union": "EUR",
    "Fiji": "FJD",
    "Falkland Islands": "FKP",
    "Faroe Islands": "FOK",
    "United Kingdom": "GBP",
    "Georgia": "GEL",
    "Guernsey": "GGP",
    "Ghana": "GHS",
    "Gibraltar": "GIP",
    "The Gambia": "GMD",
    "Guinea": "GNF",
    "Guatemala": "GTQ",
    "Guyana": "GYD",
    "Hong Kong": "HKD",
    "Honduras": "HNL",
    "Croatia": "HRK",
    "Haiti": "HTG",
    "Hungary": "HUF",
    "Indonesia": "IDR",
    "Israel": "ILS",
    "Isle of Man": "IMP",
    "India": "INR",
    "Iraq": "IQD",
    "Iran": "IRR",
    "Iceland": "ISK",
    "Jersey": "JEP",
    "Jamaica": "JMD",
    "Jordan": "JOD",
    "Japan": "JPY",
    "Kenya": "KES",
    "Kyrgyzstan": "KGS",
    "Cambodia": "KHR",
    "Kiribati": "KID",
    "Comoros": "KMF",
    "South Korea": "KRW",
    "Kuwait": "KWD",
    "Cayman Islands": "KYD",
    "Kazakhstan": "KZT",
    "Laos": "LAK",
    "Lebanon": "LBP",
    "Sri Lanka": "LKR",
    "Liberia": "LRD",
    "Lesotho": "LSL",
    "Libya": "LYD",
    "Morocco": "MAD",
    "Moldova": "MDL",
    "Madagascar": "MGA",
    "North Macedonia": "MKD",
    "Myanmar": "MMK",
    "Mongolia": "MNT",
    "Macau": "MOP",
    "Mauritania": "MRU",
    "Mauritius": "MUR",
    "Maldives": "MVR",
    "Malawi": "MWK",
    "Mexico": "MXN",
    "Malaysia": "MYR",
    "Mozambique": "MZN",
    "Namibia": "NAD",
    "Nigeria": "NGN",
    "Nicaragua": "NIO",
    "Norway": "NOK",
    "Nepal": "NPR",
    "New Zealand": "NZD",
    "Oman": "OMR",
    "Panama": "PAB",
    "Peru": "PEN",
    "Papua New Guinea": "PGK",
    "Philippines": "PHP",
    "Pakistan": "PKR",
    "Poland": "PLN",
    "Paraguay": "PYG",
    "Qatar": "QAR",
    "Romania": "RON",
    "Serbia": "RSD",
    "Russia": "RUB",
    "Rwanda": "RWF",
    "Saudi Arabia": "SAR",
    "Solomon Islands": "SBD",
    "Seychelles": "SCR",
    "Sudan": "SDG",
    "Sweden": "SEK",
    "Singapore": "SGD",
    "Saint Helena": "SHP",
    "Sierra Leone": "SLE",
    "Somalia": "SOS",
    "Suriname": "SRD",
    "South Sudan": "SSP",
    "São Tomé and Príncipe": "STN",
    "Syria": "SYP",
    "Eswatini": "SZL",
    "Thailand": "THB",
    "Tajikistan": "TJS",
    "Turkmenistan": "TMT",
    "Tunisia": "TND",
    "Tonga": "TOP",
    "Turkey": "TRY",
    "Trinidad and Tobago": "TTD",
    "Tuvalu": "TVD",
    "Taiwan": "TWD",
    "Tanzania": "TZS",
    "Ukraine": "UAH",
    "Uganda": "UGX",
    "United States": "USD",
    "Uruguay": "UYU",
    "Uzbekistan": "UZS",
    "Venezuela": "VES",
    "Vietnam": "VND",
    "Vanuatu": "VUV",
    "Samoa": "WST",
    "CEMAC": "XAF",
    "Organisation of Eastern Caribbean States": "XCD",
    "International Monetary Fund": "XDR",
    "CFA": "XOF",
    "Collectivités d'Outre-Mer": "XPF",
    "Yemen": "YER",
    "South Africa": "ZAR",
    "Zambia": "ZMW",
    "Zimbabwe": "ZWL",
    "North Korea": "KPW"
}

# Final trip city/country → currency map
trip_city_currency_map = {}

# Build from pycountry + pycountry.currencies
for country in pycountry.countries:
    try:
        country_name = country.name
        # Get official currency using alpha_2
        currency = pycountry.currencies.get(numeric=country.numeric)
        if currency:
            trip_city_currency_map[country_name] = currency.alpha_3
    except Exception:
        continue

# Merge manual + special
trip_city_currency_map.update(manual_country_currency_map)
trip_city_currency_map.update(special_currency_regions)


def get_currency_for_country(country: str) -> str:
    country_normalized = country.strip().title()
    return trip_city_currency_map.get(country_normalized, "USD")